### ISSUE TITLE
Always Opens 2nd Window on Firefox Startup

### ISSUE THREAD

**Issue by PowerWeb5** [Lej77/tree-style-tab-in-separate-window#4]
Recently, whenever this extension is enabled, it results in Firefox Nightly always opening a 2nd Window with the home page about 1-5 seconds after the browser first opens. This occurs even when I did not have Tree Style Tab in Separate Window, Tree Style Tab, or any Sidebar being shown or anything except a single window with 1 tab shown when closing Firefox last time. 

Since this only started happening recently, it may be related to Tree Style Tab's recent update to v2.7.16 on Jan 12, 2019.

On a related note, it would be nice to have an option to auto-open Tree Style Tab in Separate Window if possible, but I don't even see that option and don't think should be enabled by default, and that isn't even what is occurred here.

### Configuration

- I have "The opened window should be docked to the current window" setting enabled
    Other settings as defaults, like with "Open the sidebar page in a new window", "Create the new window beside the current window", and "Close sidebar as well", "Minimize sidebar as well", and "Simulate docking" (1000msec) all enabled.
- Tree Style Tab in Separate Window v3.1
- Tree Style Tab v2.7.16 (Jan 12, 2019)
- Firefox Nightly 66.0a1 (2019-01-17) (64-bit)
- Windows 10 Pro x64

**Comment by Lej77** [comment]
I have released a new version of the extension (v3.2) that should fix this bug (without needing to change any settings). 

I think the bug was caused by having the setting `Attempt to auto detect docked sidebar windows at extension startup.` enabled. It is located in the `Docked Window Settings`. In the new version it can be found in the groups: `Open beside current window` => `Auto detect & open sidebar windows at startup`.

**Comment by PowerWeb5** [comment]
The issue still remains with 3.2 with Tree Style Tab 2.7.17 with Firefox Nightly 67.0a1 (2019-01-29) (64-bit) on Windows 10 Pro x64.

When Firefox Nightly starts up with Tree Style Tab shown in sidebar (though not auto-opening in separate window), when Tree Style Tab in Separate Window is also installed (I believe with default settings for auto docked, etc. when used) then at least most of the time it opens up in second empty Firefox window.

**Comment by PowerWeb5** [comment]
I had all default settings (as set via Reset Settings) except for:

When sidebar page is loaded, wait this long before moving sidebar to new window = 0
Width of created window = 658

However, I also just tried Reset Settings again to reset the above to 25 and -1 respectively and, even after that, I always end up with a 2nd Firefox window being opened on Firefox startup.  I just end up seeing an annoying delay with New Tab opening as a tab in main Firefox window and then moving to a new window when I reset the delay from 0 to 25 via Reset Settings, without that fixing the issue.

Also, this seems to occur not only when built-in SIdebar starts up showing Tree Style Tabs but also if starts up showing Bookmarks or starts out hidden.

For reference, I both Firefox Options > Home > Home Page / New Window and New Tabs set to Firefox Home.

**Comment by Lej77** [comment]
@PowerAccess You can probably get around this problem by disabling the `Attempt to auto detect docked sidebar windows at extension startup` setting. It should work as a temporary workaround. I will take a look at this issue as soon as I can and attempt another fix.

**Comment by PowerWeb5** [comment]
Thanks, that does workaround the issue.
To clarify, it was never fully fixed for me, seeming to happen maybe 20% of the time with v3.2, but now for some reason recently it started happening 100% of the time.

**Comment by Lej77** [comment]
To be clear, when you start Firefox there is a second empty window that is opened? Not a window with a Tree Style Tab Sidebar page? If it is an empty window then the problem is probably because of [this code](https://github.com/Lej77/tree-style-tab-in-separate-window/blob/master/background.js#L1189). 

That code is intended to be used when Firefox is configured to restore the last session is at Firefox startup. If a docked sidebar window was the last closed window in the last session then the restored session will have only one window and that window will be a docked sidebar window which will then be auto closed and a new window is opened instead. This new window might be created by mistake under other circumstances.

**Comment by Lej77** [comment]
@PowerAccess I looked at the code and made some small changes that might fix the issue but I'm not really sure about that. Anyway in the new version (v3.3) the `Attempt to auto detect docked sidebar windows at extension startup` option is disabled by default so it shouldn't affect most people. Its probably a better idea to have it as opt-in anyway since it runs some code at Firefox startup and that can be performance bottleneck in many cases so its best to minimize that as much as possible.

**Comment by Lej77** [comment]
I just released version `5.0` of this extension. It has much better code for detecting docked "sidebar" pages at startup. This was possible since Firefox 77 allows specifying the `"sessions"` permission as an optional permission. I didn't want to require it since it isn't really needed for the extension to work and it does allow access to a lot of information that the extension doesn't really care about. Still it is necessary to be able to robustly detect what window's were opened as sidebar pages and to what window they were docked. Anyway this should mean that the `Attempt to auto detect docked sidebar windows at extension startup` option could be used by anyone that first allows the `"sessions"` permission via the extension's option page.

I did also try to add some more checks that would hopefully fix this bug even without the `"sessions"` permission but trying to guess what window was a docked "sidebar" page is really hacky so I can't be sure.
